weights: /content/gdrive/MyDrive/Sketch2aia_YoloV5/Training/yolov5m6/weights/last.pt
cfg: ''
data: /content/datasets/Sketch2aia---New-Dataset-2/data.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 1200
batch_size: 16
imgsz: 640
rect: false
resume: true
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: /content/gdrive/MyDrive/Sketch2aia_YoloV5/Training
name: yolov5m6
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: 100
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: /content/gdrive/MyDrive/Sketch2aia_YoloV5/Training/yolov5m6
